name = "GeneralizedGauss"
uuid = "05e31603-d96d-5828-bb71-68ab99de2396"
authors = ["Daan <daan.huybrechs@cs.kuleuven.be>"]
version = "0.0.1"

[deps]
BasisFunctions = "4343a256-5453-507d-8aad-01a9d7189916"
DomainSets = "5b8099bc-c8ec-5219-889f-1d9e522a28bf"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"

[compat]
BasisFunctions = "0.5"
NLsolve = "4.5.1"
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
